const JWT_SECRET = process.env.JWT_SECRET;

if (!JWT_SECRET) {
  console.error('FATAL: JWT_SECRET environment variable is required');
  process.exit(1);
}

const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET;
const STRIPE_PRICE_BASIC_YEARLY = process.env.STRIPE_PRICE_BASIC_YEARLY;
const STRIPE_PRICE_STANDARD_YEARLY = process.env.STRIPE_PRICE_STANDARD_YEARLY;
const STRIPE_PRICE_PROFESSIONAL_YEARLY = process.env.STRIPE_PRICE_PROFESSIONAL_YEARLY;
const STRIPE_PRICE_BUSINESS_YEARLY = process.env.STRIPE_PRICE_BUSINESS_YEARLY;
const WEB_FRONTEND_URL = process.env.WEB_FRONTEND_URL || 'http://localhost';

module.exports = {
  JWT_SECRET,
  STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET,
  STRIPE_PRICE_BASIC_YEARLY,
  STRIPE_PRICE_STANDARD_YEARLY,
  STRIPE_PRICE_PROFESSIONAL_YEARLY,
  STRIPE_PRICE_BUSINESS_YEARLY,
  WEB_FRONTEND_URL,
};
